# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 376)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 330, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.output = QtWidgets.QTextBrowser(Dialog)
        self.output.setGeometry(QtCore.QRect(240, 20, 256, 192))
        self.output.setObjectName("output")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(30, 20, 99, 40))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.blueCheckBox = QtWidgets.QCheckBox(self.splitter)
        self.blueCheckBox.setObjectName("blueCheckBox")
        self.greenCheckBox = QtWidgets.QCheckBox(self.splitter)
        self.greenCheckBox.setObjectName("greenCheckBox")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.pushButton.deleteLater) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Run"))
        self.blueCheckBox.setText(_translate("Dialog", "Blue Items"))
        self.greenCheckBox.setText(_translate("Dialog", "Green Items"))
